### ISSUE TITLE
Run dev  instructions

### ISSUE THREAD

**Issue by vitormarcal** [grimsi/gameyfin#157]
Can you provide information to run the application under development? What mvn commands should I run? Unfortunately I haven't been able to run it on my IDE yet :/ (IntelliJ IDEA)

**Comment by grimsi** [comment]
What exactly are your issues when trying to run Gameyfin locally?
A `mvn clean install` should compile and build both backend and frontend as well as the Java classes from the protobuf specs.
Then you can start the Gameyfin backend as you would any other Spring app and the frontend as any other Angular app (the frontend does not need to be started seperately, only if you want to develop it since the backend serves a compiled version of the frontend by default already).
Dont forget to set the IGDB credentials and set a path for your local library for testing and you're set!

Maybe I will write a more detailed guide in the wiki if necessary

**Comment by vitormarcal** [comment]
I just realized that I was editing gameyfin.yml and not gameyfin.properties to add client-id and client-secret.
My fault, thanks for the help!

**Comment by grimsi** [comment]
Great that you got it working, but it should also work with the .yml files.
