### ISSUE TITLE
Fatal glibc error: CPU does not support x86-64-v2

### ISSUE THREAD

**Issue by wonx** [grimsi/gameyfin#212]
**Describe the bug**
Since version 1.4.3, I get this error when running gameyfind from a docker container. In my case, docker runs in a virtual machine, running on proxmox. It seems to be incompatible with the default cpu used in proxmox, which is kvm64. Version 1.4.1 works just fine

**To Reproduce**
1. Use the docker compose script with the image: grimsi/gameyfin:latest
2. Run the docker container

**Expected behavior**
Gameyfin should launch.

**General info (please complete the following information):**
 - Installation method: Docker running inside Debian Buster virtual machine
 - Gameyfin version: v1.4.3

**Comment by grimsi** [comment]
Looks like youre using an older CPU.

In v1.4.3 the Docker base image for Gameyfin was switched from `openjdk:18` to `eclipse-temurin:21-jre-ubi9-minimal`.
The reason for the switch was the deprecation of the `openjdk` image.
According to the [documentation](https://hub.docker.com/_/eclipse-temurin) the new base image supports the following CPU architectures:
[amd64](https://hub.docker.com/r/amd64/eclipse-temurin/), [arm32v7](https://hub.docker.com/r/arm32v7/eclipse-temurin/), [arm64v8](https://hub.docker.com/r/arm64v8/eclipse-temurin/), [ppc64le](https://hub.docker.com/r/ppc64le/eclipse-temurin/), [s390x](https://hub.docker.com/r/s390x/eclipse-temurin/), [windows-amd64](https://hub.docker.com/r/winamd64/eclipse-temurin/)

Here is a bit more info from the Docker documentation itself: https://github.com/docker-library/official-images#architectures-other-than-amd64

It looks like there are other projects experiencing the same issue due to using a Universal Redhat base image (ubi-minimal): https://github.com/minio/minio/issues/18365#issuecomment-1789040421

So there are currently three solutions (in my order of preference with 1. being the preferred solution):
1. Switch the base image for Gameyfin again
2. Build another tag with a different base image specifically for older CPUs
3. Officially drop support for older CPUs

However I have to research which base image to switch to so that I wont run into similiar issues in the future again.
If you can support me here (by trying out different base images yourself) that would be great since my time is very limited at the moment.

**Comment by Millio345** [comment]
I'm having the same issue. Tried a few images that were linked from "openjdk" depreciation notice and "sapmachine:lts-jre-ubuntu-22.04" seems to work.

I only tested that it boots and the web ui loads, which it does, have not tested anything else. If there are any other images or things you'd like me to test, feel free to let me know.

**Comment by grimsi** [comment]
Thanks a lot! I will take another look at a suitable replacement image. The next release will be using the new image.

**Comment by Millio345** [comment]
> Edit: @Millio345 does `eclipse-temurin:21-jre-alpine` work for you as base image? I would like to keep Temurin since I use it for development.

I can confirm the `eclipse-temurin:21-jre-alpine`  base image works!
