### ISSUE TITLE
Recusively Search Folders

### ISSUE THREAD

**Issue by madeofpendletonwool** [grimsi/gameyfin#30]
Hello, I apologize if this is already a feature and I missed it in the setup video or something. I use the docker-compose method of setting things up and I have the library folder connected to my NAS. On my NAS is a games folder and then games are in folders based on system (SNES, Gamecube etc.). On program boot it doesn't seem to recursively search all the folders. Is recursive search expected? It's certainly possible I could I have set permissions up incorrectly. If not, is it possible to implement?

Thanks!

**Comment by madeofpendletonwool** [comment]
If it's helpful, here's my compose file. 'Games' is the root games folder from my NAS

version: "3"
services:
  gameyfin:
    image: grimsi/gameyfin:latest
    container_name: gameyfin
    environment:
      - GAMEYFIN_USER=username
      - GAMEYFIN_PASSWORD=password
      - GAMEYFIN_IGDB_API_CLIENT_ID=myid
      - GAMEYFIN_IGDB_API_CLIENT_SECRET=mysecret
    volumes:
      - /home/username/gameyfin/games:/opt/gameyfin-library
    ports:
      - "8080:8080"

**Comment by grimsi** [comment]
That's intended. Because games can consist of one file or multiple files or even multiple subfolders Gameyfin does not search recursively. It just doesn't know when a folder is a game and when a folder is just a subfolder containing more games or a subfolder inside of a game folder.
But Gameyfin does support adding multiple folders as library roots and you can see how it works with the second of the two docker compose example files. The library roots can even be subfolders of one another.

**Comment by madeofpendletonwool** [comment]
Ahh that totally makes sense. Thanks for the explanation. I was just able to add all the folders separately. Works great! Thanks!
