### ISSUE TITLE
Found a developer logo that's breaking the page

### ISSUE THREAD

**Issue by dsbeans** [grimsi/gameyfin#55]
Looks like some developer logos that are being pulled are not being scaled and it's breaking the game page, even at 1080 full screen. Displays correctly on my 1440 monitor though.

Looking a bit into the page, it looks like you're only controlling for height, that's probably the issue.

![image](https://user-images.githubusercontent.com/94146973/196009105-f0bb0369-f8fb-42bc-ba7e-493c60e0456c.png)

**Comment by grimsi** [comment]
Thanks for reporting this bug, I will take care of it.

The text also seems to overflow to the right, is this because your browser window is smaller than usual?
I test Gameyfin as thoroughly as possible for me on 1080p and 1440p. While lower resolutions should work I can't officially support them at the moment.

**Comment by dsbeans** [comment]
No the text appears correct on other titles, so I believe it is a side-effect of the image messing around with the margins on the page.

**Comment by grimsi** [comment]
The fixed has been implemented by @shawly and will be part of the next release (1.2.4).

Thanks for reporting the bug!
