### ISSUE TITLE
Feature: Add a desktop client

### ISSUE THREAD

**Issue by HEPOSHEIKKI** [grimsi/gameyfin#68]
### Add a desktop client to Gameyfin

_Why?_

- Users no longer have to rely on their browser for downloading
- Users don't have to move data between their download folder and game library
- The desktop app could be used to launch the games (maybe add the possibility to create custom launch methods for wine support)
- Possible update handling in the future?

_Why not?_

- Some people dislike having a dozen launchers on their device (maybe add games automatically to steam as a non-steam game if steam allows that.)
- This could easily be out of the scope of the project

_How?_

- Could this be done with just a webview and a external download manager for custom install location?
- Can we fork an existing piece of software like [Playnite](https://github.com/JosefNemec/Playnite/)
 
 
Thank you everyone working on this project, I really appreciate what you've created and this software is really valuable to me, bravo.

**Comment by grimsi** [comment]
Thanks for your feedback! There is already #20 which would bring desktop support in the form of a Playnite plugin. Personally I don't really care for this feature and I have zero experience developing plugins for Playnite, but feel free to try yourself 🙂

I will close this issue, since it's a duplicate imo (please comment if you think different).
