### ISSUE TITLE
Direct linking to network share as alternative to packing and downloading

### ISSUE THREAD

**Issue by freitagdavid** [grimsi/gameyfin#84]
**Is your feature request related to a problem? Please describe.**
It would be far faster and efficient to be able to directly copy the files from a network share rather than waiting for packaing, then unpacking on your local machine.

**Describe the solution you'd like**
There should be a setting that allows you to input your local network root share to prepend the libraries with, or even a network location setting on each of the libraries. Then you could either choose to download or click open in explorer or something along those lines and it would generate a file:// link to then open the network location.

**Comment by grimsi** [comment]
Packing should be real-time since Gameyfin does not compress the files (although it does generate a .zip file, just without any compression). But yes, if you include unpacking on the client, it will take a bit longer (although decompression should only be limited by the clients I/O throughput since it's not compressed).
Anyway I will think about it, however it does not sound like an urgent feature.

**Comment by grimsi** [comment]
I dont think this is something that Gameyfin will ever be able to do. It's just not possible to execute a file from the local browser (and it would be a huge security issue if it would be possible).
I will close this issue for now.
