### ISSUE TITLE
Gameyfin not autocompleting some games metadata, despite existing in igdb.com

### ISSUE THREAD

**Issue by wonx** [grimsi/gameyfin#88]
**Describe the bug**
Many games, specially old DOS games or Android games, can't seem to be added to gameyfin since the autocomplete can't find that title in the drop-down menu.

For instance, I bought Worms 2: Armageddon in Humble Bundle back in the day, and I have the .apk file. The file appears in the "Unmapped files" section but if I click on edit and try to autocomplete the name, there are no suggestions.

As a workaround, I was able to browse to igdb.com, search for the game (https://www.igdb.com/games/worms-2-armageddon), copy the id for the game (worms-2-armageddon) and paste it in gameyfin. It seems to work, but it's not ideal.

This behavior mostly happens with older titles, but I can't find a clear pattern. Most older DOS games seem to be affected as well.

**To Reproduce**
1. Scan the game library
2. Go to "Unmaped files"
3. Edit one of the detected games.
4. Write its name and wait for te suggestions to appear.

**Expected behavior**
The game title is found and suggested to the user. Instead, nothing happens.

**General info (please complete the following information):**
 - Installation method: Docker
 - Gameyfin version:  v1.3.1

**Comment by grimsi** [comment]
Thanks for you bug report!

The problem Gameyfin has is that it relies on IGDBs "search" API to match file/folder names to entries in the IGDB database.
However the "search" API is not really that great and only finds correct matches when the file/folder name is very close to the name of the game (even something like missing or added special characters can break it).
We already did some work on the title matching algorithm in #77 and to be honest I would like to leave it as it currently is since it seems to work for most people.
I do not want to implement a sophisticated search algorithm on top of IGDBs search engine, so there will always be some edge cases which Gameyfin will not be able to match.
I would recommend you to rename the files to more closely resemble the name of the game (for example "Worms 2: Armageddon.apk" instead of "Worms 2 Armageddon.apk").

I will close this bug for now, but feel free to comment if you have anything you want to add.
